mpv-easy/mpv-easy

mpv-easy/src/ui/components/scroll-list.tsx
mpv-tool/src/osd-overlay.ts
mpv-ui/src/render/reconciler.tsx

close https://github.com/mpv-easy/mpv-easy/issues/3

scroll-list add MaxWidthDomCache

---

mpv-easy/src/models/context.ts
mpv-tool/src/common.ts

close https://github.com/mpv-easy/mpv-easy/issues/2

tool: updatePlaylist should play once

---

mpv-easy/src/ui/speed.tsx

close https://github.com/mpv-easy/mpv-easy/issues/7

easy: fix speed mouseevent

---

mpv-tool/src/common.ts

close https://github.com/mpv-easy/mpv-easy/issues/3

tool: fix updatePlaylist play twice

---

mpv-tool/src/common.ts

close https://github.com/mpv-easy/mpv-easy/issues/11

tool: endswith support empty str

---

mpv-easy-ext/src/bin/mpv-easy-play-with.rs
mpv-easy-ext/src/common.rs
mpv-easy-ext/src/lib.rs
mpv-play-with/readme.md
mpv-tool/src/protocol-hook.ts

fix: https://github.com/mpv-easy/mpv-easy/issues/15

play-with: Simplify the protocol registration process

---

mpv-anime/src/spring.ts
mpv-canvas/src/mock.ts
mpv-easy-react/src/context.ts
mpv-easy-react/src/example/ssr.tsx
mpv-easy-react/src/ui/progress.tsx
mpv-flex/src/flex.ts
mpv-polyfill/src/index.ts
mpv-react/src/reconciler.tsx
mpv-thumbfast/src/index.ts

close: https://github.com/mpv-easy/mpv-easy/issues/38

thumbfast: add lifetime

---

mpv-crop/src/crop.tsx
mpv-crop/src/mpv-crop.tsx
mpv-easy-react/src/ui/progress.tsx
mpv-tool/src/common.ts

close: https://github.com/mpv-easy/mpv-easy/issues/44

crop: fix 44

---

Cargo.toml
mpv-clipboard-play/readme.md
mpv-clipboard-play/src/index.ts
mpv-easy-react/src/models/index.ts
mpv-tool/src/common.ts

close: https://github.com/mpv-easy/mpv-easy/issues/56

clipboard: support sub

---

mpv-tool/src/youtube.ts

close: https://github.com/mpv-easy/mpv-easy/issues/73

fix: playwith youtube support t parameter (close #73)

---

mpv-play-with/src/rules/jellyfin.ts
mpv-tool/src/rs-ext/jellyfin.ts

close: https://github.com/mpv-easy/mpv-easy/issues/79

play-with: jellyfin regex

---

mpv-cut/src/index.ts
mpv-easy-react/src/ui/progress.tsx
mpv-play-with/src/app.tsx
mpv-tool/src/ffmpeg.ts
mpv-tool/src/property.ts
mpv-tool/src/type-prop.ts

close: https://github.com/mpv-easy/mpv-easy/issues/93

mpv-cut: support remote video (close: #93)

---

mpv-easy-ext/src/common.rs
mpv-easy-react/src/ui/index.tsx

close: https://github.com/mpv-easy/mpv-easy/issues/71

play-with: add ontop when first start

---

mpv-easy-react/src/models/index.ts
mpv-easy-react/src/ui/index.tsx

close: https://github.com/mpv-easy/mpv-easy/issues/101

cancel: support cut and crop

---

mpv-easy-react/conf/input.conf
mpv-easy-react/src/models/index.ts
mpv-easy-react/src/mpv-easy-theme.ts
mpv-easy-react/src/ui/index.tsx

close: https://github.com/mpv-easy/mpv-easy/issues/102

Support preview

---

mpv-easy-react/src/mpv-easy-theme.ts
mpv-easy-react/src/ui/progress.tsx

close: https://github.com/mpv-easy/mpv-easy/issues/105

react: add preview color

---

blog/index.md
blog/mount-any-playable-link.md
mpv-clipboard-play/src/index.ts
mpv-easy-ext/src/cmd/webdav.rs
mpv-easy-react/package.json
mpv-easy-react/scripts/clipboard-play.ts
mpv-easy-react/src/icon.ts
mpv-easy-react/src/models/index.ts
mpv-easy-react/src/mpv-easy-theme.ts
mpv-easy-react/src/store.ts
mpv-easy-react/src/ui/components/mount.tsx
mpv-easy-react/src/ui/history.tsx
mpv-easy-react/src/ui/playlist.tsx
mpv-easy-react/src/ui/uosc/control.tsx
mpv-i18n/src/i18n/cn.ts
mpv-i18n/src/i18n/en.ts
mpv-polyfill/package.json
mpv-polyfill/src/corejs.ts
mpv-tool/src/rs-ext/fetch.ts
mpv-tool/src/webdav.ts
readme.md

close: https://github.com/mpv-easy/mpv-easy/issues/111

Support mount webdav

---

mpv-build/package.json
mpv-build/src/App.tsx

You can share or save your own configuration via link

build: support save config to url

---

mpv-easy-react/conf/input.conf
mpv-easy-react/src/models/index.ts
mpv-easy-react/src/mpv-easy-theme.ts
mpv-easy-react/src/store.ts
mpv-easy-react/src/ui/index.tsx
readme.md

For users who frequently use mpv-easy, they may not need cumbersome prompts

add toggle-tooltip

---

mpv-mpsm/package.json
mpv-mpsm/src/proxy.ts
mpv-mpsm/src/share.ts

mpsm: use proxy if HTTP_PROXY or HTTPS_PROXY is set

---

mpv-mpsm/src/cli.ts
mpv-mpsm/src/share.ts

https://github.com/mpv-easy/mpv-easy/issues/139

mpsm: only add undici proxy on nodejs

---

.github/workflows/release.yml
mpv-build/src/App.tsx
mpv-build/src/main.tsx
mpv-easy-react/conf/thumbfast.conf
mpv-easy-react/scripts/mpv-easy.tsx
mpv-easy-react/scripts/thumbfast.ts
mpv-mpsm/src/install.ts
mpv-mpsm/src/share.ts
mpv-thumbfast/src/index.ts
mpv-tool/src/common.ts

close: https://github.com/mpv-easy/mpv-easy/issues/148

thumbfast support uosc
